-- 
-- 2020-04-28 (Tue.) Haresh Bhatia (HB)
--
-- This is DDL to create table STG_COVID_DLY_VIZ_CNTY_ALL.
-- 
--  ------------------------------------------------------------------------------
-- 1. The file that loads this data comes from S3 bucket file-path 
--    "s3://uw211dashboard-workbucket/covid_county_full.csv"
--
-- 2. This file was downloaded by Keenan Berry from
--    "https://raw.githubusercontent.com/slu-openGIS/covid_daily_viz/master/data/county/county_full.csv"
--    The data was generated by Chris Prener (SLU Proffesor & member of STL RDA)
--
-- 3. The first row of this (data) file has column names
--    Null values are indicated by "NaN"
--    File delimiter: ","
--
--
CREATE TABLE 
          IF NOT EXISTS  uw211dashboard.public.stg_covid_dly_viz_cnty_all
(report_date         DATE,
 geo_id              VARCHAR(10),
 county              VARCHAR(30),
 state_nm            VARCHAR(30),
 cases               INTEGER,
 case_rate           NUMERIC(12,6),
 new_cases           INTEGER,
 case_avg            NUMERIC(12,6),
 death               INTEGER,
 mortality_rate      NUMERIC(12,6),
 new_deaths          INTEGER,
 death_avg           NUMERIC(12,6),
 case_fatality_rate  NUMERIC(12,6),
 PRIMARY KEY (report_date, geo_id, county, state_nm)
);

COMMENT ON TABLE uw211dashboard.public.stg_covid_dly_viz_cnty_all IS
'Table contains the covid case data (like cases, mortality, and corresponding rates and averages). The raw data for this is in file "s3://uw211dashboard-workbucket/covid_county_full.csv" that was fetched from "https://raw.githubusercontent.com/slu-openGIS/covid_daily_viz/master/data/county/county_full.csv".'
;


